### ISSUE TITLE
建议新增Tab标签页

### ISSUE THREAD

**Issue by stuaclon** [FairyEver/d2-admin#25]
首先赞作者，很漂亮，比目前vue-admin star最多那个漂亮多了，哈哈
Tab标签页,在后台管理系统中，这个还是很常用的

**Comment by FairyEver** [comment]
首先感谢认可，其实这也是我一直想做的一件事，接下来的时间我会首先实现这个功能

**Comment by FairyEver** [comment]
已经完成 #29
