### ISSUE TITLE
高级布局中的拖拽和区域划分

### ISSUE THREAD

**Issue by NikoWind** [FairyEver/d2-admin#34]
很喜欢您高级布局中的拖拽和区域划分，只是您仅仅展示了效果，没有把应用的代码公开，希望尽快更新呦！ 提一点小小的建议，虽然您组件的功能实现的没有问题，可是在查找相关组件的代码时，用觉得有些许的乱，希望可以参照 ant desige 的官网设计，把展示和代码分开，这样更加方便使用。仅仅是小建议，望采纳！

**Comment by FairyEver** [comment]
拖拽组件是 [vue-grid-layout](https://www.npmjs.com/package/vue-grid-layout) ，区域划分组件是 [vue-splitpane](https://www.npmjs.com/package/vue-splitpane)，D2Admin只是提供集成方案和优化整体效果。新发布的简化版模板 [https://github.com/FairyEver/d2-admin-start-kit](https://github.com/FairyEver/d2-admin-start-kit)
